# Generated by Django 3.2.8 on 2021-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0004_auto_20211021_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sevkiyat_Sepeti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sepetAdi', models.CharField(max_length=100)),
                ('sepetNotu', models.CharField(max_length=1000)),
                ('sepetiOlusturan', models.CharField(max_length=100)),
                ('dokmeToplami', models.IntegerField(blank=True, null=True)),
                ('sevkiyatSepetiKayitTarihSaat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
