# Generated by Django 3.2.8 on 2021-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0005_sevkiyat_sepeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevkiyat_sepeti',
            name='sepetAdi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sevkiyat_sepeti',
            name='sepetNotu',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sevkiyat_sepeti',
            name='sepetiOlusturan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
