# Generated by Django 3.2.8 on 2021-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0008_auto_20211028_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_siparis_list',
            name='fabrikaKodu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='siparisNotu2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
