# Generated by Django 3.2.8 on 2021-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0009_auto_20211028_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_siparis_list',
            name='güncellendi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='güncellenmeTarihSaati',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guven_siparis_list',
            name='sevkiyatDurumu',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
    ]
