# Generated by Django 3.2.8 on 2021-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0010_auto_20211217_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guven_siparis_list',
            name='güncellendi',
            field=models.BooleanField(),
        ),
    ]
