# Generated by Django 3.2.8 on 2021-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0011_alter_guven_siparis_list_güncellendi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guven_siparis_list',
            name='güncellendi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
