# Generated by Django 3.2.8 on 2021-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0013_alter_guven_siparis_list_güncellendi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guven_siparis_list',
            name='güncellendi',
        ),
        migrations.RemoveField(
            model_name='guven_siparis_list',
            name='güncellenmeTarihSaati',
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='guncellendi',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='guncellenmeTarihSaati',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
