# Generated by Django 3.2.8 on 2021-12-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0014_auto_20211217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guven_siparis_list',
            name='guncellendi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
