# Generated by Django 3.2.8 on 2021-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0015_alter_guven_siparis_list_guncellendi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelen_Tablosu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gelenfisNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
