# Generated by Django 3.2.8 on 2022-01-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0016_gelen_tablosu'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='alinanAdblue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='alinanyakit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='cikisKm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='dagitilan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='donusKm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='surucu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='yakitTutari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='yuklenen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
