# Generated by Django 3.2.8 on 2022-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0017_auto_20220114_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='donusTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='gidisTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
