# Generated by Django 3.2.8 on 2022-01-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0018_auto_20220114_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guven_sevkiyat_sepeti',
            old_name='alinanyakit',
            new_name='alinanYakit',
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='fark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='mazotYüzdesi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
