# Generated by Django 3.2.8 on 2022-01-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0019_auto_20220114_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_sevkiyat_sepeti',
            name='yapilanKm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
