# Generated by Django 3.2.8 on 2022-01-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0020_guven_sevkiyat_sepeti_yapilankm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guven_sevkiyat_sepeti',
            old_name='mazotYüzdesi',
            new_name='mazotYuzdesi',
        ),
    ]
