# Generated by Django 3.2.8 on 2022-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0021_rename_mazotyüzdesi_guven_sevkiyat_sepeti_mazotyuzdesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_siparis_list',
            name='siparisİzlemeNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
