# Generated by Django 3.2.8 on 2022-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0022_guven_siparis_list_siparisi̇zlemeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guven_sevkiyat_sepeti',
            name='alinanYakit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guven_sevkiyat_sepeti',
            name='yakitTutari',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
