# Generated by Django 3.2.8 on 2022-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0023_auto_20220118_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_siparis_list',
            name='makbuzNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='makbuzTarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='verilenMiktar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
