# Generated by Django 3.2.8 on 2022-02-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevkiyatApp', '0024_auto_20220119_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='guven_siparis_list',
            name='ilgili',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='tel1',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='guven_siparis_list',
            name='tel2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
